#! /bin/bash
# This file is part of nps.
# Copyright (C) 2011 Richard Kettlewell
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307
# USA
set -e
set -x

build() {
    local arch=$1
    local chroot=$2

    tar xf ${archive}
    cd ${dir}
    schroot -pc${chroot} fakeroot debian/rules build binary
    cd ..
    mv ${package}_${version}_${arch}.deb products/.
    rm -rf ${dir}
}

make distcheck

package=$(awk '/^PACKAGE_NAME =/ { print $3 }' < Makefile)
version=$(awk '/^PACKAGE_VERSION =/ { print $3 }' < Makefile)
dir=${package}-${version}
archive=${package}-${version}.tar.gz

rm -rf products ${dir}
mkdir products
cp ${archive} products/.
man -Tutf8 -l src/nps.1 | texttohtml -iT 'nps(1)' > products/nps.1.html
man -Tutf8 -l src/nps-top.1 | texttohtml -iT 'nps-top(1)' > products/nps-top.1.html

build i386 lenny32
build amd64 lenny64
ls -l products
