.TH nps-top 1
.SH NAME
nps-top \- constantly display process information
.B nps-top
.RI [ OPTIONS ]
.SH DESCRIPTION
.B nps-top
displays a constantly-updating snapshot of information about processes
running on the system.
.SH OPTIONS
.IP "\fB-o \fIFORMAT\fR, \fB-O \fIFORMAT\fR, \fB--format \fIFORMAT"
Set a specific format.
If multiple options are given then they are cumulative.
See \fBFORMATTING\fR below.
.IP "\fB-d \fISECONDS\fR, \fB--delay \fISECONDS"
Set the time between updates.
The default is 1 second.
.IP "\fB-i\fR, \fB--idle"
Display only non-idle processes.
.IP "\fB-j\fR, \fB--sysinfo \fISYSINFO"
Sets the system information format.
See \fBSYSTEM INFORMATION\fR below.
.IP \fB-M
Use megabytes rather than selecting units automatically.
.IP "\fB-s \fIORDER\fR, \fB--sort \fIORDER"
Set the order in which processes are listed.
See \fBSORTING\fR below.
.IP \fB--help
Display a usage message.
.IP \fB--help-format
Displays help for the \fB-o\fR and \fB-s\fR options.
.IP \fB--help-sysinfo
Displays help for the \fB-j\fR option.
.IP \fB--version
Display a version string.
.SH FORMATTING
The \fB-o\fR, \fB-O\fR and \fB--format\fR options specify a list of
process properties to display, separated by spaces or commas.
The available properties are:
.IP \fBaddr
The current instruction pointer (hex).
.IP \fBargs
Command line.
If these cannot be determined then the value of \fBcomm\fR is used, in
square brackets.
.IP
This corresponds to the \fBargv\fR array passed to \fBmain\fR; for a
script the first element will be the name of the interpreter and the
second element the name of the script.
.IP
Requested widths are mandatory for \fBargs\fR.
.IP \fBargsbrief
Exactly the same as \fBargs\fR but with the directory part of the
command stripped.
.IP \fBcomm
Program filename.
This corresponds to the first argument to \fBexecve\fR(3); for a
script it is the basename of the script, not the name of the
interpreter.
.IP
Requested widths are mandatory for \fBcomm\fR.
.IP \fBetime
Time elapsed since the process started.
.IP \fBflags
Flags word from the kernel (octal).
You will need a copy of the kernel sources to be able to interpret this.
.IP
If an argument is supplied it should be \fBo\fR, \fBx\fR, \fBX\fR or
\fBd\fR to for octal, hex, hex (with upper case letters) or decimal.
.IP \fBgid
Effective group ID (decimal).
.IP \fBgroup
Effective group ID as a string.
If the group name will not fit into the requested width, the numeric ID
will be used instead.
.IP \fBio
IO rate.
This is the sum of \fBread\fR and \fBwrite\fR.
.IP \fBmajflt
Major fault rate.
Major faults are page faults that require a page to be read from disk.
.IP \fBmem
The total memory (resident and swapped) used by the process.
Equivalent to \fBrss\fR+\fBswap\fR.
.IP \fBminflt
Minor fault rate.
Minor faults do not require a page to be read from disk.
.IP \fBnice
Nice value.
Higher values mean lower priority ("nicer").
.IP \fBoom
OOM score.
Higher values mean the kernel is more likely to kill the process when
memory runs out.
.IP \fBpcomm
Parent process filename.
This is the same as \fBcomm\fR but for the parent process.
.IP \fBpcpu
CPU usage, as a percentage.
(See \fBBUGS\fR below.)
.IP \fBpgid
Process group ID.
.IP \fBpid
Process ID.
.IP \fBpmem
The total memory (resident and swapped) used by the process,
scaled down to account for sharing with other processes.
Equivalent to \fBpss\fR+\fBswap\fR.
.IP \fBppid
Parent process ID.
.IP \fBpri
Priority.
.IP \fBpss
Proportional resident set size.
This the total amount of RAM used by the process, with each page's
contribution divided by the number of processes it is shared with.
.IP
Only root can read the \fBpss\fR of processes it doesn't own.
.IP \fBread
Read rate.
.IP \fBrgid
Real group ID (decimal).
.IP \fBrgroup
Real group ID as a string.
If the group name will not fit into the requested width, the numeric ID
will be used instead.
.IP \fBrss
Resident set size.
This the total amount of RAM used by the process.
.IP \fBruid
Real user ID (decimal).
.IP \fBruser
Real user ID as a string.
If the user name will not fit into the requested width, the numeric ID
will be used instead.
.IP \fBstate
Process state.
The possible states are:
.RS
.IP \fBR
Running.
.IP \fBS
Sleeping.
.IP \fBD
Disk wait.
.IP \fBZ
Exited but not yet reaped (a "zombie" process).
.IP \fBT
Traced or stopped due to a signal.
.IP \fBW
Paging.
.RE
.IP \fBstime
The time that the process started.
If an argument is supplied, it is passed to \fBstrftime\fR(3) to
format the time.
.IP \fBswap
The amount of swap used.
.IP \fBtime
The cumulative CPU time used over the process's lifetime (user and kernel).
.IP \fBtty
Controlling terminal.
The leading \fI/dev/tty\fR or \fI/dev\fR is stripped for compactness.
.IP \fBuid
Effective user ID (decimal).
.IP \fBuser
Effective user ID as a string.
If the user name will not fit into the requested width, the numeric ID
will be used instead.
.IP \fBvsz
Virtual memory size.
This is the total address space used by the process.
.IP \fBwchan
Wait channel.
.IP \fBwrite
Write rate.
second.
.SS "Column Width"
By default, every column is made wide enough for every value that
appears in it.
.PP
To request a particular width for a column, use the syntax
\fIPROPERTY\fB:\fIWIDTH\fR.
For most properties, requested widths are only advisory; if necessary
columns will be made wider to fit.
However if possible an alternative representation will be used to fit
within the requested width.
For certain properties such as \fBargs\fR requested widths are
mandatory.
.SS "Parameters"
To give a property a different heading, use the syntax
\fIPROPERTY\fB=\fIHEADING\fR.
With \fB-o\fR this only works on the last property in a single argument.
Use multiple \fB-o\fR options to work around this.
With \fB-O\fR this can be used on any or all of the properties within
an argument.
If the heading contains spaces or quotes then it must be quoted.
.PP
To supply an argument to a property, use the syntax
\fIPROPERTY\fB/\fIPARAMETER\fR.
If the argument contains spaces or quotes then it must be quoted.
.PP
If both a heading and an argument are supplied then the heading must
be first and it must be quoted.
.SS "Time Intervals"
Time intervals (such as \fBetime\fR) are represented as
[[\fIDD\fB-\fR]\fIHH\fB:\fR]\fIMM\fB:\fISS\fR, with \fIDD\fR
representing the number of days, \fIHH\fR the number of hours,
\fIMM\fR the number of minutes and \fISS\fR the number of seconds.
.PP
If a column width is requested then more compact forms may be used:
\fIDD\fB-\fIHH\fR or \fIDD\fBd\fR.
.SS "Timestamps"
Timestamps (such as \fBstime\fR) are represented as
\fIYYYY\fB-\fIMM\fB-\fIDD\fR for times outside than
the current day and \fIHH\fB:\fIMM\fB:\fISS\fR for times during the
current day.
They are always given in the local timezone.
.PP
If a column width is requested then more compact forms may be used:
\fIHH\fB:\fIMM\fR for a time in this day or \fIMM\fB-\fIDD\fR for
a date in this year.
.SS "Understanding Memory Usage"
\fBrss\fR is the resident set size of a process, i.e. the amount
physical RAM it is currently using.
However, some of that RAM may be shared with other processes, for
instance because it is used for the code of a widely used shared
library.
Therefore it can be more useful to look at the \fBpss\fR figure, the
proportional resident set size, in which every page's contribution is
divided by the number of users.
.PP
If you think you are running out of RAM and want a process to blame,
look for high \fBpss\fR figures.
.PP
\fBvsz\fR represents the total virtual memory used by the process.
This includes RAM, swap, files and anonymous mappings.
Since the dynamic linker and some other libraries like to make
inaccessible anonymous mappings, this figure can be quite misleading
as a measure of resource consumption.
.PP
\fBswap\fR represents the amount of swap space used by the process.
This includes both swapped out pages from anonymous mappings and
copy-on-write duplicates of pages mapped from files.
It does not include pages mapped from files that happen not to be in
RAM at the moment.
.PP
\fBmem\fR is the sum of \fBrss\fR and \fBswap\fR.
The same caveats apply regarding shared pages, so \fBpmem\fR, which is
the sum of \fBpss\fR and \fBswap\fR, is likely to be more useful.
.PP
The memory properties (\fBrss\fR etc) all support the following arguments:
.IP \fBK
Display in kilobytes.
.IP \fBM
Display in megabytes.
.IP \fBG
Display in gigabytes.
.IP \fBT
Display in terabytes.
.IP \fBP
Display in petabytes.
.IP \fBp
Display in pages.
.PP
With no argument, units are selected automatically.
.PP
The same applies to I/O rates, except that they are kilobytes per
seconds, etc.
.PP
The kernel support for gathering \fBpss\fR was added in Linux 2.6.25
and for \fBswap\fR in 2.6.26, so if your kernel is older than that you
will not get the correct figures.
.SS Defaults
If no formatting options at all are specified then the default is
equivalent to:
.PP
.RS
\fB-Ouser,pid,nice,rss,pcpu,read,write,tty=TTY,argsbrief=CMD
.RE
.PP
If the calling user is not \fBroot\fR then \fBread\fR and \fBwrite\fR
are omitted.
.PP
If \fB-M\fR was specified then \fBrss\fR is replaced by \fBrssM\fR.
.SH SORTING
The \fB-s\fR option specifies the properties which control the order
in which processes are displayed, separate by spaces or commas.
The available properties are listed above in \fBFORMATTING\fR.
.PP
If more than one property is specified the second and subsequent are
only considered when ordering processes which cannot be distinguished
by the first (and so on).
.PP
Each property name may be prefix with \fB+\fR to specify descending
order (the default) and \fB-\fR to specify ascending order.
.SS Defaults
If no ordering option is specified then the default is equivalent to:
.PP
.RS
\fB-s +pcpu,+io,+rss,+pmem
.RE
.SH "SYSTEM INFORMATION"
The \fB-j\fR option specifies which whole-system properties should be
displayed, separated by spaces or commas.
.PP
The available system properties are:
.IP \fBcpu
CPU usage information.
The fields are:
.RS
.TP
.B user
The percentage of time spent running all user code.
This includes \fBnice\fR and \fBguest\fR.
.TP
.B nice
The percentage of time spent running niced code.
.TP
.B guest
The percentage of time spent running guest operating systems in a virtual machine.
.TP
.B sys
The percentage of time spent in the kernel.
.TP
.B io
The percentage of time spent blocked on I/O.
.RE
.IP \fBcpus
A line equivalent to \fBcpu\fR for each individual CPU.
.IP \fBidletime
The cumulative time the system has spent idle.
.IP \fBload
The system load averages.
These three figures are the number of tasks either runnable or blocked
on disk IO averaged over 1, 5 and 15 minutes.
.IP
If an argument is supplied, it controls the number of digits shown
after the decimal point.
The default is 1.
.IP \fBmem
Memory information.
The fields are:
.RS
.TP
.B tot
Total usable memory.
This will be slightly less than the physical memory fitted, as the
kernel and some reserved memory are not included in this figure.
.TP
.B used
Memory currently in use for any purpose.
As above, the kernel is excluded.
.TP
.B free
Memory not in use for any purpose.
.TP
.B buf
Cached blocks.
.TP
.B cache
Cached files.
.RE
.IP
Use \fBmemK\fR or \fBmemM\fR to display kilobytes or megabytes.
.IP \fBprocesses
The current number of processes.
.IP \fBswap
Swap information.
The fields are:
.RS
.TP
.B tot
Total usable swap space.
.TP
.B used
Swap in use.
.TP
.B free
Swap not in use.
.TP
.B cache
Memory both in RAM and in swap.
It can be used or swapped out without IO being required.
.RE
.IP
Use \fBswapK\fR or \fBswapM\fR to display kilobytes or megabytes.
.IP \fBtime
The current time (using the local timezone).
If an argument is supplied, it is passed to \fBstrftime\fR(3) to
format the time.
.IP \fBuptime
The amount of time since the system booted.
.PP
System properties are sampled at the same time as collecting process
information, so the \fB-d\fR value defines how out of date they may be.
The exception is \fBtime\fR which always reflects the current time.
.SS Parameters
System properties may have their heading ("Time", etc) overridden, using the syntax
\fIPROPERTY\fB=\fIHEADING\fR.
If \fIHEADING\fR contains spaces or quotes then it must be quoted.
.PP
System properties may have an argument supplied, using the syntax
\fIPROPERTY\fB/\fIARGUMENT\fR.
If \fIARGUMENT\fR contains spaces or quotes then it must be quoted.
.PP
Both a heading and an argument can be set at once.
In that case the heading must come first, and it must be quoted.
For example, to change both the heading and format of the current time:
.PP
.RS
\fBtime="When"/%H:%M:%S
.RE
.PP
Headings are always followed by a colon and a space, unless they are empty.
If heading ends with one or more spaces, they are moved to after the
colon.
.PP
The memory system properties (\fBmem\fR and \fBswap\fR) support the
same arguments as the memory process properties (\fBrss\fR etc); see
above for details.
.SS Defaults
If \fB-j\fR is not specified then the default is equivalent to:
.PP
.RS
\fB-j time,uptime,processes,load,cpu,mem,swap
.RE
.PP
If \fB-M\fR was specified then \fBmem\fR and \fBswap\fR are replaced
with \fBmemM\fR and \fBswapM\fR.
.SH KEYBOARD
.SS Scrolling
If the terminal is too narrow, the process table can be panned left
and right with the following keys:
.IP "\fBright arrow\fR, \fB^F"
Moves the viewport to the right by one character, i.e. moves the
columns to the left.
.IP "\fBpage down"
Moves the viewport to the right by eight characters.
.IP "\fBleft arrow\fR, \fB^B"
Moves the viewport to the left by one character, i.e. moves the
columns to the right.
.IP "\fBpage up"
Moves the viewport to the left by eight characters.
.IP "\fB^A"
Moves the viewport all the way to the left.
.SS Commands
The following keyboard commands can also be used:
.IP "\fB^L"
Redisplay the screen.
.IP \fBd
Changes the update interval.
Equivalent to the \fB-d\fR option.
.IP \fBh
Displays on-screen help.
Press multiple times to cycle through the help pages and dismiss them.
.IP \fBi
Toggles display of idle processes.
Equivalent to the \fB-i\fR option.
.IP \fBj
Changes the list of whole-system properties.
Equivalent to the \fB-j\fR option.
.IP \fBo
Changes the list of properties to display.
Equivalent to the \fB-O\fR option.
Column headings may be quoted (and must be quoted, if they contain a
space, comma or quotes).
.IP \fBs
Changes the order specification.
Equivalent to the \fB-s\fR option.
.IP \fBq
Quits immediately.
.SS Input
When editing a value (for instance after pressing \fBd\fR) the
following keys can be used:
.IP "\fB^A"
Move the cursor to the start of the line.
.IP "\fBleft arrow\fR, \fB^B"
Move the cursor left.
.IP "\fBALT-left arrow\fR, \fBALT-B"
Move the cursor left one word.
.IP "\fB^E"
Move the cursor to the end of the line.
.IP "\fBright arrow\fR, \fB^F"
Move the cursor right.
.IP "\fBALT-right arrow\fR, \fBALT-F"
Move the cursor right one word.
.IP "\fB^L"
Redisplay the screen.
.IP "\fB^U"
Delete all the input.
.IP "\fBescape\fR, \fB^X"
Cancel the operation.
Note that \fB^X\fR will usually be more responsive than \fBescape\fR.
.IP "\fBbackspace\fR"
Delete the character to the left of the cursor.
.IP "\fBALT-backspace"
Delete the word to the left of the cursor.
.IP "\fBdelete\fR, \fB^D"
Delete the character under the cursor.
.IP "\fBALT-delete\fR, \fBALT-D"
Delete the word to the right of the cursor.
.IP "\fBreturn"
Commit the operation.
This will only have any effect if the current input is valid.
.IP "\fBup arrow\fR, \fB^P"
Scroll the help up by one line.
.IP "\fBpage up"
Scroll the help up by one page.
.IP "\fBdown arrow\fR, \fB^N"
Scroll the help down by one line.
.IP "\fBpage down"
Scroll the help down by one page.
.SH CONFIGURATION
On startup defaults are read from the file \fB$HOME/.npsrc\fR, if it
exists.
Each line has a \fIKEY\fB=\fIVALUE\fR format, with \fBtop\fR
recognizing the following keys:
.IP \fBtop_delay
The default update interval in seocnds (overridden with the \fB-d\fR
option).
.IP \fBtop_format
The default format (overridden with the \fB-o\fR or \fB-O\fR option).
Headings may be quoted (and must be quoted, if they contain a space,
comma or quotes).
The syntax is the same as when editing with the \fBo\fR key, and
different from the command-line syntax.
.IP \fBtop_order
The default order (overridden with the \fB-s\fR option).
.IP \fBtop_sysinfo
The default system information (overridden with the \fB-j\fR option).
.PP
.SH BUGS
On the first iteration, rate properties such as \fBpcpu\fR are
computed over the process's entire lifetime.
(On subsequent iterations they reflect the usage since the previous
iteration.)
.PP
The meaning of \fBflags\fR is not very clear.
.SH AUTHOR
Richard Kettlewell <rjk@greenend.org.uk>
