.TH nps-top 1
.SH NAME
nps-top \- constantly display process information
.B nps-top
.RI [ OPTIONS ]
.SH DESCRIPTION
.B nps-top
displays a constantly-updating snapshot of information about processes
running on the system.
.SH OPTIONS
.IP \fB-o \fIFORMAT
Set a specific format.
If multiple \fB-o\fR options are given then they are cumulative.
See \fBFORMATTING\fR below.
.IP \fB-i
Display only non-idle processes.
.IP \fB-I \fISYSINFO
Sets the system information format.
See \fBSYSTEM INFORMATION\fR below.
.IP \fB-s \fOORDER
Set the order in which processes are listed.
See \fBSORTING\fR below.
.IP \fB--help
Display a usage message.
.IP \fB--help-format
Displays help for the \fB-o\fR and \fB-s\fR options.
.IP \fB--help-format
Displays help for the \fB-I\fR option.
.IP \fB--version
Display a version string.
.SH FORMATTING
The \fB-o\fR option specifies a list of process properties to display,
separated by spaces or commas.
The available properties are:
.IP \fBaddr
The current instruction pointer (hex).
.IP \fBargs
Name and arguments.
If these cannot be determined then the value of \fBcomm\fR is used, in
square brackets.
.IP \fBcomm
Name.
.IP \fBetime
Time elapsed since the process started.
.IP \fBflags
Flags word from the kernel (octal).
You will need a copy of the kernel sources to be able to interpret this.
.IP \fBgid
Effective group ID (decimal).
.IP \fBgroup
Effective group ID as a string.
.IP \fBnice
Nice value.
Higher values mean lower priority ("nicer").
.IP \fBpcpu
Recent CPU usage, as a percentage.
(See \fBBUGS\fR below.)
.IP \fBpgid
Process group ID.
.IP \fBpid
Process ID.
.IP \fBppid
Parent process ID.
.IP \fBpri
Priority.
.IP \fBrgid
Real group ID (decimal).
.IP \fBrgroup
Real group ID as a string.
.IP \fBrss
Resident set size in kilobytes.
This the total amount of RAM used by the process.
.IP \fBruid
Real user ID (decimal).
.IP \fBruser
Real user ID as a string.
.IP \fBstate
Process state.
The possible states are:
.RS
.IP \fBR
Running.
.IP \fBS
Sleeping.
.IP \fBD
Disk wait.
.IP \fBZ
Exited but not yet reaped (a "zombie" process).
.IP \fBT
Traced or stopped due to a signal.
.IP \fBW
Paging.
.RE
.IP \fBstime
The time that the process started.
.IP \fBtime
The cumulative CPU time used over the process's lifetime (user and kernel).
.IP \fBtty
Controlling terminal.
The leading \fI/dev/tty\fR or \fI/dev\fR is stripped for compactness.
.IP \fBuid
Effective user ID (decimal).
.IP \fBuser
Effective user ID as a string.
.IP \fBvsz
Virtual memory size, in kilobytes.
This is the total address space used by the process.
Note that it may be misleadingly large as a measure of memory
consumption due to \fBPROT_NONE\fR mappings.
.IP \fBwchan
Wait channel.
.PP
To give a property a different heading, use the syntax
\fIPROPERTY\fB=\fIHEADING\fR.
This only works on the last property in a single argument
use multiple \fB-o\fR options to work around this.
.PP
Time intervals (such as \fBetime\fR) are represented as
[[\fIdd\fB-\fR]\fIhh\fB:\fR]\fImm\fB:\fIss\fR, with \fIdd\fR
representing the number of days, \fIhh\fR the number of hours,
\fImm\fR the number of minutes and \fIss\fR the number of seconds.
.PP
Timestamps (such as \fBstime\fR) are represented as
\fIYYYY\fB-\fIMM\fB-\fIDD\fR for times outside than
the current day and \fIHH\fB:\fIMM\fB:\fISS\fR for times during the
current day.
They are always given in the local timezone.
.PP
If no formatting options at all are specified then the default is
equivalent to:
.PP
.RS
\fB-o user,pid,rss,vsz,pcpu,tty=TTY -o time,args=CMD
.RE
.SH SORTING
The \fB-s\fR option specifies the properties which control the order
in which processes are displayed, separate by spaces or commas.
The available properties are as define above in \fBFORMATTING\fR.
.PP
If more than one property is specified the second and subsequent are
only considered when ordering processes which cannot be distinguished
by the first (and on).
.PP
Each property name may be prefix with \fB+\fR to specify descending
order (the default) and \fB-\fR to specify ascending order.
.PP
If no ordering option is specified then the default is equivalent to:
.PP
.RS
\fB -s +pcpu,+rss,+vsz
.RE
.SH "SYSTEM INFORMATION"
The \fB-I\fR option specifies which whole-system properties should be
displayed, separated by spaces or commas.
The available system properties are:
.IP \fBidletime
The cumulative time the system has spent idle.
.IP \fBprocesses
The current number of processes.
.IP \fBtime
The current time (using the local timezone).
.IP \fBuptime
The amount of time since the system booted.
.SH BUGS
On the first iteration, \fBpcpu\fR is computed over the process's
entire lifetime.
(On subsequent iterations it reflects the usage since the previous
iteration.)
.PP
The meaning of \fBflags\fR is not very clear.
.SH AUTHOR
Richard Kettlewell <rjk@greenend.org.uk>
