.TH nps-top 1
.SH NAME
nps-top \- constantly display process information
.B nps-top
.RI [ OPTIONS ]
.SH DESCRIPTION
.B nps-top
displays a constantly-updating snapshot of information about processes
running on the system.
.SH OPTIONS
.IP \fB-o \fIFORMAT
Set a specific format.
If multiple \fB-o\fR options are given then they are cumulative.
See \fBFORMATTING\fR below.
.IP \fB-i
Display only non-idle processes.
.IP \fB-I \fISYSINFO
Sets the system information format.
See \fBSYSTEM INFORMATION\fR below.
.IP \fB-s \fIORDER
Set the order in which processes are listed.
See \fBSORTING\fR below.
.IP \fB-d \fISECONDS
Set the time between updates.
The default is 1 second.
.IP \fB-M
Use megabytes rather than kilobytes.
.IP \fB--help
Display a usage message.
.IP \fB--help-format
Displays help for the \fB-o\fR and \fB-s\fR options.
.IP \fB--help-sysinfo
Displays help for the \fB-I\fR option.
.IP \fB--version
Display a version string.
.SH FORMATTING
The \fB-o\fR option specifies a list of process properties to display,
separated by spaces or commas.
The available properties are:
.IP \fBaddr
The current instruction pointer (hex).
.IP \fBargs
Name and arguments.
If these cannot be determined then the value of \fBcomm\fR is used, in
square brackets.
.IP \fBcomm
Name.
.IP \fBetime
Time elapsed since the process started.
.IP \fBflags
Flags word from the kernel (octal).
You will need a copy of the kernel sources to be able to interpret this.
.IP \fBgid
Effective group ID (decimal).
.IP \fBgroup
Effective group ID as a string.
.IP \fBio
IO rate, in kilobytes per second.
This is the sum of \fBread\fR and \fBwrite\fR.
.IP \fBioM
IO rate, in megabytes per second.
.IP \fBmajflt
Major fault rate, in kilobytes per second.
Major faults are page faults that require a page to be read from disk.
.IP \fBmajfltM
Major fault rate, in megabytes per second.
.IP \fBmajfltP
Major fault rate, in pages per second.
.IP \fBminflt
Minor fault rate, in kilobytes per second.
Minor faults do not require a page to be read from disk.
.IP \fBminfltM
Minor fault rate, in megabytes per second.
.IP \fBminfltP
Minor fault rate, in pages per second.
.IP \fBnice
Nice value.
Higher values mean lower priority ("nicer").
.IP \fBoom
OOM score.
Higher values mean the kernel is more likely to kill the process when
memory runs out.
.IP \fBpcpu
CPU usage, as a percentage.
(See \fBBUGS\fR below.)
.IP \fBpgid
Process group ID.
.IP \fBpid
Process ID.
.IP \fBppid
Parent process ID.
.IP \fBpri
Priority.
.IP \fBread
Read rate, in kilobytes per second.
.IP \fBreadM
Read rate, in megabytes per second.
.IP \fBrgid
Real group ID (decimal).
.IP \fBrgroup
Real group ID as a string.
.IP \fBrss
Resident set size in kilobytes.
This the total amount of RAM used by the process.
.IP \fBrssM
Resident set size in megabytes.
.IP \fBruid
Real user ID (decimal).
.IP \fBruser
Real user ID as a string.
.IP \fBstate
Process state.
The possible states are:
.RS
.IP \fBR
Running.
.IP \fBS
Sleeping.
.IP \fBD
Disk wait.
.IP \fBZ
Exited but not yet reaped (a "zombie" process).
.IP \fBT
Traced or stopped due to a signal.
.IP \fBW
Paging.
.RE
.IP \fBstime
The time that the process started.
.IP \fBtime
The cumulative CPU time used over the process's lifetime (user and kernel).
.IP \fBtty
Controlling terminal.
The leading \fI/dev/tty\fR or \fI/dev\fR is stripped for compactness.
.IP \fBuid
Effective user ID (decimal).
.IP \fBuser
Effective user ID as a string.
.IP \fBvsz
Virtual memory size, in kilobytes.
This is the total address space used by the process.
Note that it may be misleadingly large as a measure of memory
consumption due to \fBPROT_NONE\fR mappings.
.IP \fBvszM
Virtual memory size, in megabytes.
.IP \fBwchan
Wait channel.
.IP \fBwrite
Write rate, in kilobytes per second.
.IP \fBwriteM
Write rate, in megabytes per second.
.PP
To give a property a different heading, use the syntax
\fIPROPERTY\fB=\fIHEADING\fR.
This only works on the last property in a single argument
use multiple \fB-o\fR options to work around this.
.PP
Time intervals (such as \fBetime\fR) are represented as
[[\fIdd\fB-\fR]\fIhh\fB:\fR]\fImm\fB:\fIss\fR, with \fIdd\fR
representing the number of days, \fIhh\fR the number of hours,
\fImm\fR the number of minutes and \fIss\fR the number of seconds.
.PP
Timestamps (such as \fBstime\fR) are represented as
\fIYYYY\fB-\fIMM\fB-\fIDD\fR for times outside than
the current day and \fIHH\fB:\fIMM\fB:\fISS\fR for times during the
current day.
They are always given in the local timezone.
.PP
If no formatting options at all are specified then the default is
equivalent to:
.PP
.RS
\fB-o user,pid,nice,rss,pcpu,read,write,tty=TTY -o args=CMD
.RE
.PP
If the calling user is not \fBroot\fR then \fBread\fR and \fBwrite\fR
are omitted.
.PP
If \fB-M\fR was specified then \fBrss\fR is replaced by \fBrssM\fR.
.SH SORTING
The \fB-s\fR option specifies the properties which control the order
in which processes are displayed, separate by spaces or commas.
The available properties are listed above in \fBFORMATTING\fR.
.PP
If more than one property is specified the second and subsequent are
only considered when ordering processes which cannot be distinguished
by the first (and so on).
.PP
Each property name may be prefix with \fB+\fR to specify descending
order (the default) and \fB-\fR to specify ascending order.
.PP
If no ordering option is specified then the default is equivalent to:
.PP
.RS
\fB-s +pcpu,+io,+rss,+vsz
.RE
.SH "SYSTEM INFORMATION"
The \fB-I\fR option specifies which whole-system properties should be
displayed, separated by spaces or commas.
The available system properties are:
.IP \fBcpu
CPU usage information.
The fields are:
.RS
.TP
.B user
The percentage of time spent running all user code.
This includes \fBnice\fR and \fBguest\fR.
.TP
.B nice
The percentage of time spent running niced code.
.TP
.B guest
The percentage of time spent running guest operating systems in a virtual machine.
.TP
.B sys
The percentage of time spent in the kernel.
.TP
.B io
The percentage of time spent blocked on I/O.
.RE
.IP \fBidletime
The cumulative time the system has spent idle.
.IP \fBload
The system load averages.
These three figures are the number of tasks either runnable or blocked
on disk IO averaged over 1, 5 and 15 minutes.
.IP \fBmem
Memory information (kilobytes).
The fields are:
.RS
.TP
.B tot
Total usable memory.
This will be slightly less than the physical memory fitted, as the
kernel and some reserved memory are not included in this figure.
.TP
.B used
Memory currently in use for any purpose.
As above, the kernel is excluded.
.TP
.B free
Memory not in use for any purpose.
.TP
.B buf
Cached blocks.
.TP
.B cache
Cached files.
.RE
.IP \fBmemM
Memory information (megabytes).
.IP \fBprocesses
The current number of processes.
.IP \fBswap
Swap information (kilobytes).
The fields are:
.RS
.TP
.B tot
Total usable swap space.
.TP
.B used
Swap in use.
.TP
.B free
Swap not in use.
.TP
.B cache
Memory both in RAM and in swap.
It can be used or swapped out without IO being required.
.RE
.IP \fBswapM
Swap information (megabytes).
.IP \fBtime
The current time (using the local timezone).
.IP \fBuptime
The amount of time since the system booted.
.SH KEYBOARD
.SS Scrolling
If the terminal is too narrow, the process table can be panned left
and right with the following keys:
.IP "\fBright arrow\fR, \fB^F"
Moves the viewport to the right by one character, i.e. moves the
columns to the left.
.IP "\fBpage down"
Moves the viewport to the right by eight characters.
.IP "\fBleft arrow\fR, \fB^B"
Moves the viewport to the left by one character, i.e. moves the
columns to the right.
.IP "\fBpage up"
Moves the viewport to the left by eight characters.
.IP "\fB^A"
Moves the viewport all the way to the left.
.SS Commands
The following keyboard commands can also be used:
.IP "\fB^L"
Redisplay the screen.
.IP \fBd
Changes the update interval.
Equivalent to the \fB-d\fR option.
.IP \fBh
Displays on-screen help.
Press multiple times to cycle through the help pages and dismiss them.
.IP \fBo
Changes the list of properties to display.
Similar to the \fB-o\fR option except column headings may be quoted
(and must be quoted, if they contain a space, comma or quotes).
.IP \fBs
Changes the order specification.
Equivalent to the \fB-s\fR option.
.IP \fBq
Quits immediately.
.SS Input
When editing a value (for instance after pressing \fBd\fR) the
following keys can be used:
.IP "\fB^A"
Move the cursor to the start of the line.
.IP "\fBleft arrow\fR, \fB^B"
Move the cursor right.
.IP "\fB^E"
Move the cursor to the end of the line.
.IP "\fBright arrow\fR, \fB^F"
Move the cursor right.
.IP "\fB^L"
Redisplay the screen.
.IP "\fB^U"
Delete all the input.
.IP "\fBbackspace\fR, \fB^D"
Delete the character to the left of the cursor.
.IP "\fBdelete"
Delete the character under the cursor.
.IP "\fBescape"
Cancel the operation.
.IP "\fBreturn"
Commit the operation.
This will only have any effect if the current input is valid.
.SH CONFIGURATION
On startup defaults are read from the file \fB$HOME/.npsrc\fR, if it
exists.
Each line has a \fIKEY\fB=\fIVALUE\fR format, with \fBtop\fR
recognizing the following keys:
.IP \fBtop_delay
The default update interval in seocnds (overridden with the \fB-d\fR
option).
.IP \fBtop_format
The default format (overridden with the \fB-o\fR option).
Headings may be quoted (and must be quoted, if they contain a space,
comma or quotes).
The syntax is the same as when editing with the \fBo\fR key, and
different from the command-line syntax.
.IP \fBtop_order
The default order (overriden with the \fB-s\fR option).
.IP \fBtop_sysinfo
The default system information (overriden with the \fB-I\fR option).
.PP
.SH BUGS
On the first iteration, rate properties such as \fBpcpu\fR are
computed over the process's entire lifetime.
(On subsequent iterations they reflect the usage since the previous
iteration.)
.PP
The meaning of \fBflags\fR is not very clear.
.SH AUTHOR
Richard Kettlewell <rjk@greenend.org.uk>
