.TH nps 1
.SH NAME
nps \- list processes
.SH SYNOPSIS
.B nps
.RI [ OPTIONS ]
.RI [ MATCHES ]
.SH DESCRIPTION
.B nps
writes a snapshot of information about processes running on the system.
.SH OPTIONS
.IP \fB-a
Select processes which have a controlling terminal.
.IP "\fB-A\fR, \fB-e"
Select all processes.
.IP "\fB-C \fINAME"
Select processes by name.
.IP
Equivalent to \fBcomm=:\fINAME\fR (see \fBMATCH EXPRESSIONS\fR below).
.IP \fB-d
Select all processes that are not session leaders.
.IP \fB-f
Set the "full" output format.
.IP \fB-l
Set the "long" output format.
.IP "\fB-g \fILIST"
Select all processes whose sessions are in \fILIST\fR.
.IP "\fB-G \fILIST"
Select all processes whose real group ID is in \fILIST\fR (by name or
number).
.IP \fB-H
Hierarchical display.
.IP "\fB-n \fIANYTHING"
Ignored.
.IP "\fB-o \fIFORMAT\fR, \fB-O \fIFORMAT"
Set a specific format.
If multiple \fB-o\fR or \fB-O\fR options are given then they are cumulative.
See \fBFORMATTING\fR below.
.IP "\fB-p \fILIST"
Select all the processes in \fILIST\fR.
.IP "\fB-t \fILIST"
Select all the processes whose controlling terminals are in \fILIST\fR.
Terminal names may be abbreviated by ommitting the initial \fB/dev\fR.
.IP "\fB-u \fILIST"
Select all the processes whose effective user ID is in \fILIST\fR (by
name or number).
.IP "\fB-U \fILIST"
Select all the processes whose real user ID is in \fILIST\fR (by
name or number).
.IP \fB-w
Don't truncate output.
.IP \fB--help
Display a usage message.
.IP \fB--help-format
Displays help for the \fB-o\fR option.
.IP \fB--version
Display a version string.
.PP
All \fILIST\fR options consists of elements separated by spaces or
commas.
.PP
Process selection is cumulative, i.e. if multiple process selection
options are given then any process which is selected by at least
one of them is selected.
If no selection options are given then only processes that share an
effective UID and terminal with the current process are selected.
.SH "MATCH EXPRESSIONS"
Following the options may appear one or more match expressions.
These are general-purpose process selection options and come in several
forms.
.PP
As with other process selection options, the effect of match
expressions is cumulative.
.SS "Display Match Expressions"
These match expressions match the value exactly as displayed.
For numeric properties, this isn't usually very useful.
For example, \fBrss=1048576\fR will never match, because it will
always be \fB1M\fR in that case.
.PP
The first is \fIPROPERTY\fB=\fIVALUE\fR and matches only if the named
property exactly matches the given value.
For instance, \fBcomm=kvm\fR can be used to match \fBkvm\fR processes
only.
.PP
The second is \fIPROPERTY\fB~\fIREGEXP\fR and matches if the named
property matches the extended POSIX regexp.
For instance \fBargs~dbus\fR will match \fBdbus-daemon\fR,
\fBdbus-launch\fR, etc.
.SS "Value Match Expressions"
These match expressions match the value as represented internally,
with the following consequences:
.IP \(bu
Numbers are given their exact value, rather than rounding to
kilobytes, megabytes, etc.
For instance, \fBrss==1048576\fR will match processes with an RSS of
exactly one megabyte.
.IP \(bu
TTY paths are not abbreviated.
.IP \(bu
Times are represnted as second counts.
.PP
The possible match expressions are \fIPROPERTY\fB<\fIVALUE\fR,
\fIPROPERTY\fB<=\fIVALUE\fR, \fIPROPERTY\fB>\fIVALUE\fR,
\fIPROPERTY\fB>=\fIVALUE\fR for ordering comparisons,
\fIPROPERTY\fB==\fIVALUE\fR to test for equality and
\fIPROPERTY\fB<>\fIVALUE\fR or \fIPROPERTY\fB!=\fIVALUE\fR to test for
inequality.
.PP
In all cases, numbers are compared as numbers and strings are compared
lexicographically.
Where the \fIVALUE\fR is a number, it may be represented in hex (using
a \fB0x\fR prefix) or octal (using a \fB0\fR prefix) and suffixed with
\fBK\fR, \fBM\fR, \fBG\fR, \fBT\fR or \fBP\fR to represent kilobytes
up to petabytes, or \fBp\fR to represent pages.
(This is possible even when it doesn't make a great deal of sense,
e.g. \fBpid<1K\fR.)
.PP
For example, to list processes with an RSS of at least one megabyte,
you might use:
.PP
.RS
\fBnps -o user,pid,rss,tty,comm 'rss>=1M'
.RE
.SS "Quoting"
Since value match expressions include shell metacharacters, some
shell quoting may be required.
.PP
In order to distinguish between (for instance) \fB==\fR and \fB=\fR
where the first character of the \fIVALUE\fR is an \fB=\fR sign, any
match operator may be followed by a single \fB:\fR.
When the value is a shell variable it is advisable to always include
the colon, for example:
.PP
.RS
\fBnps -o user,pid,rss,tty,comm "comm=:${COMMAND}"
.RE
.SH FORMATTING
The \fB-o\fR option specifies a list of process properties to display,
separated by spaces or commas.
The available properties are:
.IP \fBaddr
The current instruction pointer (hex).
.IP \fBargs
Command line.
If these cannot be determined then the value of \fBcomm\fR is used, in
square brackets.
.IP
This corresponds to the \fBargv\fR array passed to \fBmain\fR; for a
script the first element will be the name of the interpreter and the
second element the name of the script.
.IP
Requested widths are mandatory for \fBargs\fR.
.IP \fBargsbrief
Exactly the same as \fBargs\fR but with the directory part of the
command stripped.
.IP \fBcomm
Program filename.
This corresponds to the first argument to \fBexecve\fR(3); for a
script it is the basename of the script, not the name of the
interpreter.
.IP
Requested widths are mandatory for \fBcomm\fR.
.IP \fBetime
Time elapsed since the process started.
.IP \fBflags
Flags word from the kernel (octal).
You will need a copy of the kernel sources to be able to interpret this.
.IP \fBflagsx
Flags word from the kernel (hex).
.IP \fBgid
Effective group ID (decimal).
.IP \fBgroup
Effective group ID as a string.
If the group name will not fit into the requested width, the numeric ID
will be used instead.
.IP \fBio
IO rate.
This is the sum of \fBread\fR and \fBwrite\fR.
.IP
Use \fBioK\fR or \fBioM\fR to display kilobytes or megabytes per second.
.IP \fBmajflt
Major fault rate.
Major faults are page faults that require a page to be read from disk.
.IP
Use \fBmajfltK\fR or \fBmajfltM\fR to display kilobytes or megabytes
per second, or \fBmajfltP\fR to display pages per second
.IP \fBmem
The total memory (resident and swapped) used by the process.
Equivalent to \fBrss\fR+\fBswap\fR.
.IP
Use \fBmemK\fR or \fBmemM\fR to display kilobytes or megabytes.
.IP \fBminflt
Minor fault rate.
Minor faults do not require a page to be read from disk.
.IP
Use \fBminfltK\fR or \fBminfltM\fR to display kilobytes or megabytes
per second, or \fBminfltP\fR to display pages per second
.IP \fBnice
Nice value.
Higher values mean lower priority ("nicer").
.IP \fBoom
OOM score.
Higher values mean the kernel is more likely to kill the process when
memory runs out.
.IP \fBpcpu
CPU usage, as a percentage.
(See \fBBUGS\fR below.)
.IP \fBpgid
Process group ID.
.IP \fBpid
Process ID.
.IP \fBpmem
The total memory (resident and swapped) used by the process,
scaled down to account for sharing with other processes.
Equivalent to \fBpss\fR+\fBswap\fR.
.IP
Use \fBpmemK\fR or \fBpmemM\fR to display kilobytes or megabytes.
.IP \fBppid
Parent process ID.
.IP \fBpri
Priority.
.IP \fBpss
Proportional resident set size.
This the total amount of RAM used by the process, with each page's
contribution divided by the number of processes it is shared with.
.IP
Only root can read the \fBpss\fR of processes it doesn't own.
.IP
Use \fBpssK\fR or \fBpssM\fR to display kilobytes or megabytes.
.IP \fBread
Read rate.
.IP
Use \fBreadK\fR or \fBreadM\fR to display kilobytes or megabytes per
second.
.IP \fBrgid
Real group ID (decimal).
.IP \fBrgroup
Real group ID as a string.
If the group name will not fit into the requested width, the numeric ID
will be used instead.
.IP \fBrss
Resident set size.
This the total amount of RAM used by the process.
.IP
Use \fBrssK\fR or \fBrssM\fR to display kilobytes or megabytes.
.IP \fBruid
Real user ID (decimal).
.IP \fBruser
Real user ID as a string.
If the user name will not fit into the requested width, the numeric ID
will be used instead.
.IP \fBstate
Process state.
The possible states are:
.RS
.IP \fBR
Running.
.IP \fBS
Sleeping.
.IP \fBD
Disk wait.
.IP \fBZ
Exited but not yet reaped (a "zombie" process).
.IP \fBT
Traced or stopped due to a signal.
.IP \fBW
Paging.
.RE
.IP \fBstime
The time that the process started.
.IP \fBswap
The amount of swap used.
.IP
Use \fBswapK\fR or \fBswapM\fR to display kilobytes or megabytes.
.IP \fBtime
The cumulative CPU time used over the process's lifetime (user and kernel).
.IP \fBtty
Controlling terminal.
The leading \fI/dev/tty\fR or \fI/dev\fR is stripped for compactness.
.IP \fBuid
Effective user ID (decimal).
.IP \fBuser
Effective user ID as a string.
If the user name will not fit into the requested width, the numeric ID
will be used instead.
.IP \fBvsz
Virtual memory size.
This is the total address space used by the process.
.IP
Use \fBvszK\fR or \fBvszM\fR to display kilobytes or megabytes.
.IP \fBwchan
Wait channel.
.IP \fBwrite
Write rate.
.IP
Use \fBwriteK\fR or \fBwriteM\fR to display kilobytes or megabytes per
second.
.SS "Column Width"
By default, every column is made wide enough for every value that
appears in it.
.PP
To request a particular width for a column, use the syntax
\fIPROPERTY\fB:\fIWIDTH\fR.
For most properties, requested widths are only advisory; if necessary
columns will be made wider to fit.
However if possible an alternative representation will be used to fit
within the requested width.
For certain properties such as \fBargs\fR requested widths are
mandatory.
.SS "Headings"
To give a property a different heading, use the syntax
\fIPROPERTY\fB=\fIHEADING\fR.
With \fB-o\fR this only works on the last property in a single argument.
Use multiple \fB-o\fR options to work around this.
With \fB-O\fR this can be used on any or all of the properties within
an argument.
If the heading contains spaces or quotes then it must be quoted.
.SS "Time Intervals"
Time intervals (such as \fBetime\fR) are represented as
[[\fIDD\fB-\fR]\fIHH\fB:\fR]\fIMM\fB:\fISS\fR, with \fIDD\fR
representing the number of days, \fIHH\fR the number of hours,
\fIMM\fR the number of minutes and \fISS\fR the number of seconds.
.PP
If a column width is requested then more compact forms may be used:
\fIDD\fB-\fIHH\fR or \fIDD\fBd\fR.
.SS "Timestamps"
Timestamps (such as \fBstime\fR) are represented as
\fIYYYY\fB-\fIMM\fB-\fIDD\fR for times outside than
the current day and \fIHH\fB:\fIMM\fB:\fISS\fR for times during the
current day.
They are always given in the local timezone.
.PP
If a column width is requested then more compact forms may be used:
\fIHH\fB:\fIMM\fR for a time in this day or \fIMM\fB-\fIDD\fR for
a date in this year.
.SS "Understanding Memory Usage"
\fBrss\fR is the resident set size of a process, i.e. the amount
physical RAM it is currently using.
However, some of that RAM may be shared with other processes, for
instance because it is used for the code of a widely used shared
library.
Therefore it can be more useful to look at the \fBpss\fR figure, the
proportional resident set size, in which every page's contribution is
divided by the number of users.
.PP
If you think you are running out of RAM and want a process to blame,
look for high \fBpss\fR figures.
.PP
\fBvsz\fR represents the total virtual memory used by the process.
This includes RAM, swap, files and anonymous mappings.
Since the dynamic linker and some other libraries like to make
inaccessible anonymous mappings, this figure can be quite misleading
as a measure of resource consumption.
.PP
\fBswap\fR represents the amount of swap space used by the process.
This includes both swapped out pages from anonymous mappings and
copy-on-write duplicates of pages mapped from files.
It does not include pages mapped from files that happen not to be in
RAM at the moment.
.PP
\fBmem\fR is the sum of \fBrss\fR and \fBswap\fR.
The same caveats apply regarding shared pages, so \fBpmem\fR, which is
the sum of \fBpss\fR and \fBswap\fR, is likely to be more useful.
.PP
The unadorned memory properties (and IO rates) all append \fBK\fR,
\fBM\fR, \fBG\fR or \fBT\fR to the figure to indicate what units are
in use.
Use \fBrssK\fR, \fBrssM\fR, etc to select particular units.
.PP
The kernel support for gathering \fBpss\fR was added in Linux 2.6.25
and for \fBswap\fR in 2.6.26, so if your kernel is older than that you
will not get the correct figures.
.SS Defaults
If no formatting options at all are specified then the default is
equivalent to:
.PP
.RS
\fB-Opid,tty=TTY,time,comm=CMD
.RE
.PP
The \fB-f\fR option is equivalent to:
.PP
.RS
\fB-Ouser=UID,pid,ppid,pcpu=C,stime,tty=TTY,time,comm=CMD
.RE
.PP
The \fB-l\fR option is equivalent to:
.PP
.RS
\fB-Oflags,state,uid,pid,ppid,pcpu=C,pri,nice,addr,vszK=SZ,
wchan,tty=TTY,time,argsbrief=CMD
.RE
.SH CONFIGURATION
On startup defaults are read from the file \fB$HOME/.npsrc\fR, if it
exists.
Each line has a \fIKEY\fB=\fIVALUE\fR format, with \fBps\fR
recognizing the following keys:
.IP \fBps_format
The default format.
.IP \fBps_f_format
The format to use if \fB-f\fR is specified.
.IP \fBps_l_format
The format to use if \fB-l\fR is specified.
.PP
In this file, unlike in command line arguments, headings may be quoted
(and must be quoted, if they contain a space, comma or quotes).
.SH ENVIRONMENT
.TP
.B COLUMNS
The maximum line length.
If \fBCOLUMNS\fR is not set then window width is used when writing to
a terminal, and no truncation takes place when writing to any other
kind of output.
.SH BUGS
Rate properties such as \fBpcpu\fR is computed over the process's
entire lifetime, which is stretching the definition of "recent".
.PP
The meaning of \fBflags\fR is not very clear.
.SH STANDARDS
Intended to follow SUS v4.
.SH AUTHOR
Richard Kettlewell <rjk@greenend.org.uk>
