#! /bin/sh
# This file is part of nps.
# Copyright (C) 2012, 2017 Richard Kettlewell
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307
# USA
set -e

mode=--test
verbose=false

# Options
while test $# -gt 0; do
  option="$1"
  shift
  case "$option" in
  --regenerate | --test | --force-regenerate )
    mode="$option"
    ;;
  --verbose )
    verbose=true
    ;;
  * )
    echo >&2 "ERROR: unknown option '$option'"
    exit 1
    ;;
  esac
done

# Consistent localtime behavior
export TZ=UTC

# Find test data
if test "${srcdir}" = ""; then
  TESTDATA=testdata
else
  TESTDATA=${srcdir}/testdata
fi

try() {
  local name="$1"
  local opts
  shift
  opts="--set-proc ${TESTDATA}/0 --set-proc2 ${TESTDATA}/1 --set-self 17274 --set-time 1334151627 --set-users ${TESTDATA}/passwd --set-group ${TESTDATA}/group --set-dev ${TESTDATA}/devices --set-uid 1000 --sort -pid,-tid"
  if $verbose; then
    echo ./nps $opts "$@" '>'$name.out
  fi
  ./nps $opts "$@" >$name.out
  case $mode in
  --force-regenerate )
    mv $name.out ${TESTDATA}/$name.expect
    ;;
  --regenerate )
    if [ -e ${TESTDATA}/$name.expect ]; then
      diff -u ${TESTDATA}/$name.expect $name.out
      rm -f $name.out
    else
      mv $name.out ${TESTDATA}/$name.expect
    fi
    ;;
  --test )
    if diff -u ${TESTDATA}/$name.expect $name.out; then
      rm -f $name.out
    else
      exit=1
    fi
    ;;
  esac
}

try raw
try with-terminal -a
try all -A
try all -e
try all --all
try not-session-leader -d
try csv --all --csv
try full -ef
try full --all --full
try long -el
try long --all --long
try forest -eH
try forest --all --forest
try threads -eL
try threads --all --threads
try help --help
try help-format --help-format
try help-match --help-match

try ancestor --ancestor 358
try ancestor2 --ancestor 358,2621
try ppid --ppid 358
try ppid2 --ppid 358,2621
try pid -p 358
try pid2 --pid 358,2621
try comm -C udevd

try sortrss -e -o pid,rss,vsize,comm --sort rss
try sortrss -e -o pid,rss,vsize,comm --sort +rss
try sortrssasc -e -o pid,rss,vsize,comm --sort -rss
try sortvsize -e -o pid,rss,vsize,comm --sort vsize

try tty1 -f -t /dev/pts/0
try tty1 -f -t pts/0
try tty2 -f -t /dev/pts/3
try tty2 -f -t pts/3
try tty3 -f -t /dev/pts/0,/dev/pts/3

try user1 -opid,user,ruser,comm -u root
try user2 -opid,user,ruser,comm -u richard
try user3 -opid,user,ruser,comm -u news
try user4 -opid,user,ruser,comm -U root

try group1 -opid,group,rgroup,comm --group root
try group2 -opid,group,rgroup,comm --group daemon
try group3 -opid,group,rgroup,comm --group richard,news
try group4 -opid,group,rgroup,comm -G root
try group5 -opid,group,rgroup,comm -G daemon

# TODO:

# -o, -O
# -w
# -n

# match expressions...

# --poll

exit $exit
